import React, { ReactElement } from 'react'
import Head from 'next/head'
import styles from './index.module.css'
import Sign from './Sign'
import Header from './Header'
import Hero from './Hero'

export default function HomePage(): ReactElement {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />

      <main className={styles.main}>
        <Sign />
      </main>

      <footer className={styles.footer}></footer>
    </>
  )
}
