import React, { ReactElement } from 'react'
import Head from 'next/head'
import styles from './index.module.css'
import Sign from './Sign'
import Header from './Header'

export default function HomePage(): ReactElement {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />

        <main className={styles.main}>
          <Sign />
        </main>

        <footer className={styles.footer}></footer>
      </div>
    </>
  )
}
